<a href="https://colab.research.google.com/github/puzlike/expert-octo-telegram/blob/main/MyNotebook1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd
import random

DF1 = pd.DataFrame()

for i in range(5):
    m = np.array([[random.randint(0, 10), random.randint(0, 10)],
                 [random.randint(0, 10), random.randint(0, 10)],
                 [random.randint(0, 10), random.randint(0, 10)]])
    print(f'm = {m}')

    DF2 = pd.DataFrame(m)
    print(f'DF2 = \n{DF2}')
    DF1 = DF1.append(DF2)
 
    print(f'DF1 = \n{DF1.reset_index(drop=True)}\n')
    

m = [[7 7]
 [4 3]
 [8 2]]
DF2 = 
   0  1
0  7  7
1  4  3
2  8  2
DF1 = 
   0  1
0  7  7
1  4  3
2  8  2

m = [[7 4]
 [1 5]
 [4 1]]
DF2 = 
   0  1
0  7  4
1  1  5
2  4  1
DF1 = 
   0  1
0  7  7
1  4  3
2  8  2
3  7  4
4  1  5
5  4  1

m = [[7 4]
 [1 4]
 [5 2]]
DF2 = 
   0  1
0  7  4
1  1  4
2  5  2
DF1 = 
   0  1
0  7  7
1  4  3
2  8  2
3  7  4
4  1  5
5  4  1
6  7  4
7  1  4
8  5  2

m = [[6 0]
 [1 6]
 [0 4]]
DF2 = 
   0  1
0  6  0
1  1  6
2  0  4
DF1 = 
    0  1
0   7  7
1   4  3
2   8  2
3   7  4
4   1  5
5   4  1
6   7  4
7   1  4
8   5  2
9   6  0
10  1  6
11  0  4

m = [[5 3]
 [2 9]
 [0 4]]
DF2 = 
   0  1
0  5  3
1  2  9
2  0  4
DF1 = 
    0  1
0   7  7
1   4  3
2   8  2
3   7  4
4   1  5
5   4  1
6   7  4
7   1  4
8   5  2
9   6  0
10  1  6
11  0  4
12  5  3
13  2  9
14  0  4

